{
  uid: "woodjack",
  firstName: "Jack",
  data: dataArr;
}

dataArr [dataObjects] // There will be a maximum of one dataObject per day.

dataObject:
{
  date: "01171998", // Uses getMonth(), getDate(), and getYear() from Javascript Date object.
  totals: {
    trans_total:
    cons_total:
    energy_total:
    food_total:
    waste_total:
    water_total:
  },
  location: {} // Location object generated by http://freegeoip.net/json/
}
