language: node_js
node_js:
    - "10"

cache:
  directories:
      - node_modules

script:
  - npm run build

deploy:
- provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  fqdn: myco2.sustainability.oregonstate.edu
- provider: s3
  access_key_id: $S3_ACCESS_ID
  secret_access_key: $S3_ACCESS_KEY
  bucket: "carbon-calculator"
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
- provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs4.3"
  handler_name: "handler"
- provider: script
  script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      sam package --template-file backend/template.yaml --s3-bucket osu-so-serverless-builds --output-template-file packaged.yaml
      sam deploy --template-file packaged.yaml --stack-name carbon-calculator --capabilities CAPABILITY_IAM
    fi
  skip_cleanup: true
  on:
    branch: master
