language: node_js
node_js:
    - "10"

cache:
  directories:
      - node_modules

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_ID
  secret_access_key: $S3_ACCESS_KEY
  bucket: "carbon-calculator"
  skip_cleanup: true
  local_dir: dist
  on:
all_branches: true
