language: node_js
python:
- '2.7'
node_js:
- '10'
install:
- pip install --user awscli
- pip install --user aws-sam-cli
- npm --prefix dependencies/nodejs install
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
- provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  fqdn: myco2.sustainability.oregonstate.edu
- provider: s3
  access_key_id: "$S3_ACCESS_ID"
  secret_access_key: "$S3_ACCESS_KEY"
  bucket: carbon-calculator
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
deploy:
- provider: script
  script:
  - sam package --template-file backend/template.yaml --s3-bucket osu-so-serverless-builds --output-template-file packaged.yaml
  - sam deploy --template-file packaged.yaml --stack-name carbon-calculator --capabilities CAPABILITY_IAM
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: WYryTGpmLKt8qXFBI0clSuXtXWOD8kywDI4z6f/UhKQeAQzqJScoBM4EgAgWT/iRIs9AMIrOX41P7c9eLBKos5CUYedbk/+1KjUpwmed15EUrPuAIxQiaEu+X0DvA28XRQYKvhaqqNdAZ5gJsTP6yMrWLw1bS1ZUjZK7n8PpTwCbeKeYVEZlwL/PeWQux9xVS7/TRGKz9nHkHV0QBSLKNgjwHJoFobwr3BLZdiEkiL+NhXcuGoI3dd9jcxvCUh4GlXKd5M63R7eHVlw1bmfCaVORyPdBQsZzO7JbRoL/l0YjZCE2TpL0c0+PzyX/zIikx+XU+5HxCjVtBHq6jsJagxId7M7VhQ1FtSi6Fee62wEmHjrHi50F2pbn055ISZnqos1OfwumDxr+d+IMnop7n3ZEv+RXTt6X444I6bZkEOr/vkhPEEtgRnTc98HTp72/4/h+mGxVdX//Coof8U73us+Gc0ZJteYMyrtKqEPfOn5fIKbVm2dK3lgJNN2XUgDX4AG+e7Uu5eyenN1KI1m1fWSO+yA4gAfs2zGkGa/UiS36ualiqSaPncdsgqBd5g2U2kczOc6nTCNI80ubT+lTs9GkImJ/z47HVHWqBoP67+9fyGosFjhY12ngWuzp2yRLUi9tI9WTSMYzES+BGoNEJgnPDkfrkiPKdChpvPLUlpA=
  - secure: SD3Hz7uqT+mYfxZ7tuEUjCCjNRayaY2w/9IJwknG0vdvnXS1qTZdzydUSj/wq6xE0CiMu/F8p2jj0GLDkSXd7geTchNKqsoUhfstD5LbC32oQ+0EQh83eHOdkkTcyPDWWiNr91egdZLVO0BcKHFOchxTTzKkzMvhc/2JIQLEDtllt61q1ZcnbGXwHlrrK/WX2B6fGpSV2AzUa02/ea2H6dqxGSoIZF/CMe1/rCjCMPlLrf/9PVH3N28aCdiKIsuuLAMBvBsXHX6PQ3jb/FnfMwjYZB/02CDE1wziwK38Kj8b868Qc88o9T7ncqfLahB9hY+5s7ZaoIn2eL0PIcK9QVqkA8U63Lir+4lmupGr5o7bJNXCT3yb+Ur39NNGIXKBHdvP7RYFDkO0YCuSJoMkvv1lwx+pKo3ZbyRgsDQzaoT/4bZv2wPdqBSn6Xc5wN+dEZDvdeOpQgKH0uWwyvXPGsx9WGpcYjxGDB+TvtVG66d1GW3vJ4jUcSOrVTHAiHSsA8DUMC8GsVlhU8dceG5+idXkoZy+LnWPAlyJaJCkC0lXMjrFHPnRSPj2ZJVUUq+dpnhJ++LRetmulBj9r+l0m7O7bDmsfYav6k/4lQUgVdLKsYWXz6XgOxVlP8GN8N9vaV0lsjRK6F3CtyiSKK89RbizOrky4GpuhzlA/MBpCAc=
