AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'carbon-calculator

  Contains the serverless api business logic for the Carbon Calculator.

  '
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowOrigin: '''http://localhost:8080'''
Parameters:
  LambdaCommonLayer:
    Type: String
    Default: arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:29
Resources:
  ccUserDataDownload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/3df2e338874ddf59b215bd09b8ae6bbc
      Handler: app.download
      Runtime: nodejs12.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        test:
          Type: Api
          Properties:
            Path: /download
            Method: get
  ccUserDataUpload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/3df2e338874ddf59b215bd09b8ae6bbc
      Handler: app.upload
      Runtime: nodejs12.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        test:
          Type: Api
          Properties:
            Path: /upload
            Method: post
  ccUserDeleteData:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/3df2e338874ddf59b215bd09b8ae6bbc
      Handler: app.delete
      Runtime: nodejs12.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        test:
          Type: Api
          Properties:
            Path: /delete
            Method: get
  ccQuestionDataDownload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/3df2e338874ddf59b215bd09b8ae6bbc
      Handler: app.questions
      Runtime: nodejs12.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        test:
          Type: Api
          Properties:
            Path: /questions
            Method: get
