AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'carbon-calculator

  Contains the serverless api business logic for the Carbon Calculator.

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  LambdaCommonLayer:
    Type: String
    Default: arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:29
Resources:
  ccUserDataDownload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/fafe984188efe7e12996c527f0fa3772
      Handler: app.download
      Runtime: nodejs10.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        cc:
          Type: Api
          Properties:
            Path: /download
            Method: get
  ccUserDataUpload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/fafe984188efe7e12996c527f0fa3772
      Handler: app.upload
      Runtime: nodejs10.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        cc:
          Type: Api
          Properties:
            Path: /upload
            Method: post
  ccUserDeleteData:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/fafe984188efe7e12996c527f0fa3772
      Handler: app.delete
      Runtime: nodejs10.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        cc:
          Type: Api
          Properties:
            Path: /delete
            Method: get
  ccQuestionDataDownload:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - AmazonDynamoDBFullAccess
      CodeUri: s3://osu-so-serverless-builds/fafe984188efe7e12996c527f0fa3772
      Handler: app.questions
      Runtime: nodejs10.x
      Layers:
      - Ref: LambdaCommonLayer
      Events:
        cc:
          Type: Api
          Properties:
            Path: /questions
            Method: get
