AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  carbon-calculator

  Contains the serverless api business logic for the Carbon Calculator.

Globals:
  Function:
    Timeout: 3

Parameters:
  LambdaCommonLayer:
    Type: String
    Default: arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:58

Resources:
  getCategory:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: app/category
      Handler: app.getCategory
      Runtime: nodejs10.x
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        cc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /category
            Method: get
  postCategory:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: app/category
      Handler: app.postCategory
      Runtime: nodejs10.x
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        cc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /category
            Method: post
  getData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: app/data
      Handler: app.getData
      Runtime: nodejs10.x
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        cc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /data
            Method: get
  postData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: app/data
      Handler: app.postData
      Runtime: nodejs10.x
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        cc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /data
            Method: post
  deleteData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: app/data
      Handler: app.deleteData
      Runtime: nodejs10.x
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        cc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /data
            Method: delete
